"""Fetch and format structured summary data from stitch, grouped by application type.

This module produces human-readable text mirroring the C++ SummaryWriter output
style.  The structured summary text itself is never seen or generated by a model,
but the ``build_operational_prompt`` function builds an LLM prompt from the same
data for a short natural-language operational sentence.
"""
from __future__ import annotations

import logging
from typing import Any

from sprout.exceptions import StitchAPIError
from sprout.kg.utils import _stitch_base, get_json, load_applications

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Task-specific featured metrics
# ---------------------------------------------------------------------------
# Maps a detected task to the metrics that should appear in the task
# highlights section.  Each entry is (app_type_key, metric_key, source)
# where *source* is ``"impl_avg"`` or ``"top"`` (matching the two buckets
# in ``_extract_summary_metrics``).  The special source ``"hybrids"``
# pulls the hybrid list from the raw summary payload.
TASK_HIGHLIGHTS: dict[str, list[tuple[str, str, str]]] = {
    "plant": [
        ("seeding", "population", "impl_avg"),
        ("seeding", "singulation", "impl_avg"),
        ("seeding", "hybrids", "hybrids"),
    ],
    "harvest": [
        ("global", "acres", "top"),
        ("global", "average_speed", "top"),
        ("harvest", "moisture", "top"),
        ("harvest", "dryyieldavg", "top"),
    ],
    "spray": [
        ("liquid", "rate", "top"),
    ],
}

# Maps a detected task to the metrics used in the LLM operational prompt.
# Same tuple shape as TASK_HIGHLIGHTS: (app_type_key, metric_key, source).
# Spray includes global acres/speed which aren't in its display highlights.
OPERATIONAL_METRICS: dict[str, list[tuple[str, str, str]]] = {
    "plant": [
        ("seeding", "population", "impl_avg"),
        ("seeding", "singulation", "impl_avg"),
        ("seeding", "hybrids", "hybrids"),
    ],
    "harvest": [
        ("global", "acres", "top"),
        ("global", "average_speed", "top"),
        ("harvest", "moisture", "top"),
        ("harvest", "dryyieldavg", "top"),
    ],
    "spray": [
        ("global", "acres", "top"),
        ("global", "average_speed", "top"),
        ("liquid", "rate", "top"),
    ],
}

_TASK_LABELS: dict[str, str] = {
    "plant": "planting",
    "harvest": "harvest",
    "spray": "spraying",
}


def _detect_task(app_type_keys: set[str]) -> str | None:
    """Infer the run task from the set of application type keys present."""
    if "seeding" in app_type_keys:
        return "plant"
    if "harvest" in app_type_keys:
        return "harvest"
    if "liquid" in app_type_keys:
        return "spray"
    return None


def _format_hybrids(hybrids: list[dict[str, Any]]) -> str | None:
    """Format the hybrids list: names if <=2, count otherwise."""
    if not hybrids:
        return None
    names = []
    for h in hybrids:
        name_obj = h.get("name", {})
        if isinstance(name_obj, dict):
            n = name_obj.get("value")
        else:
            n = name_obj
        if n:
            names.append(str(n))
    if not names:
        return None
    if len(names) <= 2:
        return ", ".join(names)
    return f"{len(names)} varieties"


def _format_key(key: str) -> str:
    """Turn a snake_case metric key into a readable label.

    ``singulation_pct_avg`` → ``Singulation Pct Avg``
    """
    return key.replace("_", " ").title()


def _extract_value(value_obj: Any) -> float | None:
    """Extract a numeric value from a metric's value object.

    Stitch metrics can be structured in several ways:

    * ``{"implement_average": 1.23}``  — flat average
    * ``{"label": "...", "unit": "...", "value": 1.23}``  — labelled scalar
    * ``1.23``  — bare number

    Returns the first non-None number found, or ``None``.
    """
    if isinstance(value_obj, (int, float)):
        return float(value_obj)
    if not isinstance(value_obj, dict):
        return None
    # Prefer implement_average when present.
    impl = value_obj.get("implement_average")
    if impl is not None:
        return float(impl)
    # Fall back to a bare "value" field (labelled scalar from to_pair).
    val = value_obj.get("value")
    if isinstance(val, (int, float)):
        return float(val)
    return None


def _pick_label(key: str, name: str | None, value_obj: Any) -> str:
    """Choose the best human-readable label for a metric.

    Prefers the protobuf ``label`` embedded in the value object, then ``name``
    from the metric entry (unless it is too short / ambiguous), falling back to
    a formatted version of the ``key``.
    """
    # The C++ to_pair helper embeds {"label": "...", ...} in the value object.
    if isinstance(value_obj, dict):
        label = value_obj.get("label")
        if isinstance(label, str) and len(label) > 1:
            unit = value_obj.get("unit")
            if unit:
                return f"{label} ({unit})"
            return label
    # Fall back to the metric-level name if it looks informative.
    if name and len(name) > 2:
        return name
    return _format_key(key)


def _extract_summary_metrics(payload: dict[str, Any]) -> list[dict[str, Any]]:
    """Extract metrics from a ``/local/summary/{app_id}`` response.

    The summary endpoint returns the C++ SummaryWriter output.  Metrics live in
    two places:

    * ``implement_average`` — dict of key → ``{label, unit, value}``
    * Top-level ``to_pair`` fields (e.g. ``acres``, ``average_speed``)

    Returns the same shape as ``load_application_metrics_with_values``.
    """
    results: list[dict[str, Any]] = []
    skip_keys = {"type", "name", "row_average", "hybrids", "mass",
                 "pass_count", "seconds_applying", "time_finished",
                 "time_started", "implement_average"}

    # 1. implement_average metrics (primary — singulation, population, etc.)
    impl_avg = payload.get("implement_average")
    if isinstance(impl_avg, dict):
        for key, value_obj in impl_avg.items():
            if not isinstance(value_obj, dict):
                continue
            val = value_obj.get("value")
            if not isinstance(val, (int, float)):
                continue
            label = _pick_label(key, None, value_obj)
            results.append({"key": key, "name": label, "value": float(val), "raw_value": value_obj})

    # 2. Top-level to_pair fields (acres, average_speed, etc.)
    for key, value_obj in payload.items():
        if key in skip_keys:
            continue
        if not isinstance(value_obj, dict) or "value" not in value_obj:
            continue
        val = value_obj.get("value")
        if not isinstance(val, (int, float)):
            continue
        label = _pick_label(key, None, value_obj)
        results.append({"key": key, "name": label, "value": float(val), "raw_value": value_obj})

    return results


def _fetch_raw_summary(application_id: str) -> dict[str, Any]:
    """Fetch the raw ``/local/summary/{app_id}`` JSON payload."""
    url = f"{_stitch_base()}/local/summary/{application_id}"
    payload = get_json(url, retries=1, timeout=10)
    if not isinstance(payload, dict):
        return {}
    return payload


def load_application_summary(application_id: str) -> list[dict[str, Any]]:
    """Fetch the C++ SummaryWriter output for an application.

    Calls ``GET /local/summary/{application_id}`` which returns the full
    summary with ``implement_average`` containing properly labelled metrics
    (singulation, population, etc.).

    Returns a list of dicts:
    ``{"key": str, "name": str, "value": float, "raw_value": Any}``.
    """
    payload = _fetch_raw_summary(application_id)
    if not payload:
        return []
    return _extract_summary_metrics(payload)


def load_application_metrics_with_values(application_id: str) -> list[dict[str, Any]]:
    """Fetch metrics for an application from the metrics endpoint (fallback).

    Returns a list of dicts:
    ``{"key": str, "name": str, "value": float | None, "raw_value": Any}``.
    """
    url = f"{_stitch_base()}/local/metrics/{application_id}"
    payload = get_json(url)
    results: list[dict[str, Any]] = []
    for m in payload.get("metrics", []):
        key = m.get("key")
        if not key:
            continue
        value_obj = m.get("value", {})
        extracted = _extract_value(value_obj)
        label = _pick_label(key, m.get("name"), value_obj)
        results.append({"key": key, "name": label, "value": extracted, "raw_value": value_obj})
    return results


def fetch_structured_summary() -> list[dict[str, Any]]:
    """Fetch summary data grouped by application from stitch.

    Tries the ``/local/summary/{app_id}`` endpoint first (C++ SummaryWriter
    output with full metric detail), falling back to ``/local/metrics/{app_id}``
    if the summary endpoint is unavailable.

    Returns a list of application dicts, each containing:

    * ``application_name``
    * ``application_type_key``
    * ``application_type_name``
    * ``metrics`` — list of ``{"key", "name", "value"}``
    * ``raw_summary`` — the raw ``/local/summary`` JSON (for hybrids, etc.)
    """
    apps = load_applications()
    result: list[dict[str, Any]] = []
    for app in apps:
        app_id = app.get("application_id", "")
        app_name = app.get("name", "")
        app_type = app.get("type", {})
        type_key = app_type.get("key", "unknown") if isinstance(app_type, dict) else "unknown"
        type_name = app_type.get("name", app_name) if isinstance(app_type, dict) else app_name

        metrics: list[dict[str, Any]] = []
        raw_summary: dict[str, Any] = {}
        try:
            raw_summary = _fetch_raw_summary(app_id)
            metrics = _extract_summary_metrics(raw_summary) if raw_summary else []
        except (StitchAPIError, Exception) as exc:
            logger.debug("Summary endpoint failed for %s, trying metrics: %s", app_id, exc)
        if not metrics:
            try:
                metrics = load_application_metrics_with_values(app_id)
            except StitchAPIError:
                continue

        if any(m["value"] is not None for m in metrics):
            result.append(
                {
                    "application_name": app_name,
                    "application_type_key": type_key,
                    "application_type_name": type_name,
                    "metrics": metrics,
                    "raw_summary": raw_summary,
                }
            )
    return result


def _build_task_highlights(apps_data: list[dict[str, Any]]) -> list[str]:
    """Build the task-specific highlight lines from application data.

    Returns a list of formatted strings (one per featured metric), or an
    empty list if no task could be detected or no featured metrics were found.
    """
    type_keys = {app["application_type_key"] for app in apps_data}
    task = _detect_task(type_keys)
    if task is None:
        return []

    highlights_spec = TASK_HIGHLIGHTS.get(task, [])
    if not highlights_spec:
        return []

    # Index apps by type key (first match wins for a given type).
    apps_by_type: dict[str, dict[str, Any]] = {}
    for app in apps_data:
        tk = app["application_type_key"]
        if tk not in apps_by_type:
            apps_by_type[tk] = app

    lines: list[str] = []
    for app_type_key, metric_key, source in highlights_spec:
        app = apps_by_type.get(app_type_key)
        if app is None:
            continue

        if source == "hybrids":
            raw = app.get("raw_summary", {})
            hybrids = raw.get("hybrids")
            if isinstance(hybrids, list) and hybrids:
                formatted = _format_hybrids(hybrids)
                if formatted:
                    lines.append(f"  Seed Hybrids: {formatted}")
            continue

        # Look up the metric in the app's already-extracted metrics list.
        for m in app.get("metrics", []):
            if m["key"] == metric_key and m["value"] is not None:
                lines.append(f"  {m['name']}: {m['value']:,.2f}")
                break

    return lines


def format_structured_summary(apps_data: list[dict[str, Any]]) -> str:
    """Format application metric data as human-readable text."""
    if not apps_data:
        return ""

    lines: list[str] = ["", "--- Structured Summary ---", ""]

    # Task-specific highlights at the top.
    highlight_lines = _build_task_highlights(apps_data)
    if highlight_lines:
        lines.append("Run Highlights")
        lines.extend(highlight_lines)
        lines.append("")

    for app in apps_data:
        type_name = app["application_type_name"]
        app_name = app["application_name"]
        header = f"{type_name} ({app_name})" if app_name != type_name else type_name
        lines.append(header)

        for m in app["metrics"]:
            if m["value"] is None:
                logger.debug(
                    "Structured summary: skipping %s (no extractable value), raw=%r",
                    m["key"],
                    m.get("raw_value"),
                )
                continue
            lines.append(f"  {m['name']}: {m['value']:,.2f}")

        lines.append("")  # blank line between sections

    lines.append("--- End Structured Summary ---")
    return "\n".join(lines)


def build_operational_prompt(apps_data: list[dict[str, Any]]) -> str | None:
    """Build an LLM prompt for a short operational sentence from application data.

    Returns a prompt string asking the LLM to summarise the run's key metrics
    in one natural-language sentence, or ``None`` if no task could be detected
    or no metrics were found.
    """
    type_keys = {app["application_type_key"] for app in apps_data}
    task = _detect_task(type_keys)
    if task is None:
        return None

    specs = OPERATIONAL_METRICS.get(task, [])
    if not specs:
        return None

    # Index apps by type key.
    apps_by_type: dict[str, dict[str, Any]] = {}
    for app in apps_data:
        tk = app["application_type_key"]
        if tk not in apps_by_type:
            apps_by_type[tk] = app

    data_lines: list[str] = []
    for app_type_key, metric_key, source in specs:
        app = apps_by_type.get(app_type_key)
        if app is None:
            continue

        if source == "hybrids":
            raw = app.get("raw_summary", {})
            hybrids = raw.get("hybrids")
            if isinstance(hybrids, list) and hybrids:
                formatted = _format_hybrids(hybrids)
                if formatted:
                    data_lines.append(f"- Hybrids: {formatted}")
            continue

        for m in app.get("metrics", []):
            if m["key"] == metric_key and m["value"] is not None:
                data_lines.append(f"- {m['name']}: {m['value']:,.2f}")
                break

    if not data_lines:
        return None

    task_label = _TASK_LABELS.get(task, task)
    return (
        "Summarize this agricultural operation in one short natural-language sentence. "
        "Start by naming (eg: Spraying operation, Seeding Operation, Harvest Operation). "
        "Omit indefinite article 'a'. Do not use other nouns for operation (eg: don't use 'pass'). "
        "Use approximate values (e.g., \"about\", \"around\", \"near\", \"~\"). "
        "Do not use bullet points or JSON.\n\n"
        f"Task: {task_label}\n"
        "Data:\n"
        + "\n".join(data_lines)
    )


def build_structured_summary() -> str:
    """Fetch and format the structured summary from stitch.

    Returns formatted text, or ``""`` if the data is unavailable.
    """
    try:
        apps_data = fetch_structured_summary()
    except Exception as exc:
        logger.warning("Structured summary: fetch failed: %s", exc)
        return ""
    return format_structured_summary(apps_data)
